### ISSUE TITLE
TF-M non-secure address start is not aligned on SPU region size

### ISSUE THREAD

**Issue by szczys** [circuitdojo/nrf9160-feather-examples-and-drivers#12]
When building the `tracker` sample on `v2.2.x` I receive the following error:

```console
-- Build files have been written to: /home/mike/golioth-compile/circuitdojo/nfed/samples/tracker/build
[0/375] Performing build step for 'tfm'
[19/46] Building C object platform/CMakeFiles/platform_s.dir/home/mike/golioth-compile/circuitdojo/nrf/modules/tfm/tfm/boards/common/assert.o
FAILED: platform/CMakeFiles/platform_s.dir/home/mike/golioth-compile/circuitdojo/nrf/modules/tfm/tfm/boards/common/assert.o 
/home/mike/.zephyrtools/toolchain/zephyr-sdk-0.15.1/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc -DBL1_HEADER_SIZE=0x000 -DBL1_TRAILER_SIZE=0x000 -DBL2_HEADER_SIZE=0x000 -DBL2_TRAILER_SIZE=0x000 -DCONFIG_HW_UNIQUE_KEY -DCONFIG_HW_UNIQUE_KEY_RANDOM -DCONFIG_TFM_BUILDING_SPE=1 -DCONFIG_TFM_DOORBELL_API=1 -DCONFIG_TFM_FP=2 -DCONFIG_TFM_LAZY_STACKING -DCONFIG_TFM_PARTITION_META -DDAUTH_CHIP_DEFAULT -DEXT_API_MAGIC="" -DFIRMWARE_INFO_MAGIC="" -DMBEDTLS_CONFIG_FILE=\"nrf-config.h\" -DMBEDTLS_USER_CONFIG_FILE=\"nrf-config-user.h\" -DMCUBOOT_IMAGE_NUMBER=1 -DNRF9160_XXAA -DNRF_ALLOW_NON_SECURE_RESET -DNRF_HW_INIT_NRF_PERIPHERALS -DNRF_HW_INIT_RESET_ON_BOOT -DNRF_NS_STORAGE -DNRF_SKIP_FICR_NS_COPY_TO_RAM -DPLATFORM_DEFAULT_BL1 -DPSA_CRYPTO_SECURE -DTFM_CRYPTO_AEAD_MODULE_DISABLED -DTFM_CRYPTO_ASYM_ENCRYPT_MODULE_DISABLED -DTFM_CRYPTO_ASYM_SIGN_MODULE_DISABLED -DTFM_CRYPTO_CIPHER_MODULE_DISABLED -DTFM_CRYPTO_HASH_MODULE_DISABLED -DTFM_CRYPTO_KEY_DERIVATION_MODULE_DISABLED -DTFM_CRYPTO_KEY_MODULE_DISABLED -DTFM_CRYPTO_MAC_MODULE_DISABLED -DTFM_FIH_PROFILE_OFF -DTFM_INTERNAL_TRUSTED_STORAGE_SERVICE_SID=0x00000070 -DTFM_LVL=1 -DTFM_PARTITION_CRYPTO -DTFM_PARTITION_LOG_LEVEL=TFM_PARTITION_LOG_LEVEL_SILENCE -DTFM_PARTITION_PLATFORM -DTFM_PSA_API -DTFM_SPM_LOG_LEVEL=TFM_SPM_LOG_LEVEL_SILENCE -D__NRF_TFM__ -I/home/mike/golioth-compile/circuitdojo/modules/tee/tf-m/trusted-firmware-m/platform/ext/target/nordic_nrf/common/core/. -I/home/mike/golioth-compile/circuitdojo/modules/tee/tf-m/trusted-firmware-m/platform/ext/target/nordic_nrf/common/core/native_drivers -I/home/mike/golioth-compile/circuitdojo/modules/hal/nordic/nrfx -I/home/mike/golioth-compile/circuitdojo/modules/hal/nordic/nrfx/mdk -I/home/mike/golioth-compile/circuitdojo/modules/hal/nordic/nrfx/drivers/include -I/home/mike/golioth-compile/circuitdojo/modules/tee/tf-m/trusted-firmware-m/platform/ext/target/nordic_nrf/common/core/common -I/home/mike/golioth-compile/circuitdojo/modules/tee/tf-m/trusted-firmware-m/platform/.. -I/home/mike/golioth-compile/circuitdojo/modules/tee/tf-m/trusted-firmware-m/platform/ext/target/nordic_nrf/common/core/services/include -I/home/mike/golioth-compile/circuitdojo/modules/tee/tf-m/trusted-firmware-m/platform/ext/target/nordic_nrf/common/nrf9160/. -I/home/mike/golioth-compile/circuitdojo/nrf/modules/tfm/tfm/boards/partition -I/home/mike/golioth-compile/circuitdojo/nfed/samples/tracker/build/tfm/../zephyr/include/generated -I/home/mike/golioth-compile/circuitdojo/nrf/modules/tfm/tfm/boards/board -I/home/mike/golioth-compile/circuitdojo/nfed/samples/tracker/build/tfm/../zephyr/misc/generated/syscalls_links/include -I/home/mike/golioth-compile/circuitdojo/zephyr/include/zephyr -I/home/mike/golioth-compile/circuitdojo/zephyr/include -I/home/mike/golioth-compile/circuitdojo/nrf/modules/tfm/tfm/boards/services/include -I/home/mike/golioth-compile/circuitdojo/nrf/include -I/home/mike/golioth-compile/circuitdojo/nrf/modules/tfm/tfm/boards/include -I/home/mike/golioth-compile/circuitdojo/nrf/include/tfm -I/home/mike/golioth-compile/circuitdojo/modules/tee/tf-m/trusted-firmware-m/platform/ext/accelerator/interface -I/home/mike/golioth-compile/circuitdojo/modules/tee/tf-m/trusted-firmware-m/secure_fw/partitions/lib/sprt/include -I/home/mike/golioth-compile/circuitdojo/modules/tee/tf-m/trusted-firmware-m/secure_fw/include -I/home/mike/golioth-compile/circuitdojo/modules/tee/tf-m/trusted-firmware-m/secure_fw/spm/include -I/home/mike/golioth-compile/circuitdojo/modules/tee/tf-m/trusted-firmware-m/platform/./ext -I/home/mike/golioth-compile/circuitdojo/modules/tee/tf-m/trusted-firmware-m/platform/./ext/cmsis -I/home/mike/golioth-compile/circuitdojo/modules/tee/tf-m/trusted-firmware-m/platform/./ext/common -I/home/mike/golioth-compile/circuitdojo/modules/tee/tf-m/trusted-firmware-m/platform/./ext/driver -I/home/mike/golioth-compile/circuitdojo/modules/tee/tf-m/trusted-firmware-m/platform/./include -I/home/mike/golioth-compile/circuitdojo/modules/tee/tf-m/trusted-firmware-m/lib/fih/inc -I/home/mike/golioth-compile/circuitdojo/modules/tee/tf-m/trusted-firmware-m/interface/include -I/home/mike/golioth-compile/circuitdojo/nfed/samples/tracker/build/tfm/generated/interface/include -I/home/mike/golioth-compile/circuitdojo/modules/tee/tf-m/trusted-firmware-m/secure_fw/spm/cmsis_psa -I/home/mike/golioth-compile/circuitdojo/modules/tee/tf-m/trusted-firmware-m/secure_fw/spm/include/interface -I/home/mike/golioth-compile/circuitdojo/modules/tee/tf-m/trusted-firmware-m/secure_fw/spm/arch/include -I/home/mike/golioth-compile/circuitdojo/modules/tee/tf-m/trusted-firmware-m/secure_fw/spm/cmsis_psa/arch -I/home/mike/golioth-compile/circuitdojo/modules/tee/tf-m/trusted-firmware-m/secure_fw/spm -I/home/mike/golioth-compile/circuitdojo/modules/tee/tf-m/trusted-firmware-m/secure_fw/spm/cmsis_psa/include -I/home/mike/golioth-compile/circuitdojo/nrfxlib/crypto/nrf_oberon/include/mbedtls -I/home/mike/golioth-compile/circuitdojo/nrfxlib/crypto/nrf_oberon/include -I/home/mike/golioth-compile/circuitdojo/modules/tee/tf-m/trusted-firmware-m/secure_fw/partitions/crypto -I/home/mike/golioth-compile/circuitdojo/nfed/samples/tracker/build/tfm/secure_fw/partitions/crypto/mbedcrypto/nrf_security_src/include/generated -I/home/mike/golioth-compile/circuitdojo/nrfxlib/nrf_security/tfm/../include -I/home/mike/golioth-compile/circuitdojo/nrfxlib/nrf_security/tfm/../include/mbedtls -I/home/mike/golioth-compile/circuitdojo/nrfxlib/nrf_security/tfm/../include/psa -I/home/mike/golioth-compile/circuitdojo/modules/crypto/mbedtls/include -I/home/mike/golioth-compile/circuitdojo/modules/crypto/mbedtls/include/mbedtls -I/home/mike/golioth-compile/circuitdojo/modules/crypto/mbedtls/include/psa -I/home/mike/golioth-compile/circuitdojo/modules/crypto/mbedtls/library -I/home/mike/golioth-compile/circuitdojo/nrfxlib/nrf_security/tfm/../../crypto/nrf_oberon/include -I/home/mike/golioth-compile/circuitdojo/nrfxlib/nrf_security/tfm/../../crypto/nrf_oberon/include/mbedtls -I/home/mike/golioth-compile/circuitdojo/nrfxlib/nrf_security/tfm/../../crypto/nrf_oberon/include/psa -isystem /home/mike/golioth-compile/circuitdojo/nrfxlib/crypto/nrf_cc310_platform/include -mcpu=cortex-m33+nodsp -g --specs=nano.specs -Wall -Wno-format -Wno-return-type -Wno-unused-but-set-variable -c -fdata-sections -ffunction-sections -fno-builtin -fshort-enums -funsigned-char -mthumb -nostdlib -std=c99 -gdwarf-4 -g -mcmse -mfloat-abi=hard -mfpu=fpv5-sp-d16 -Wno-unused-value -MD -MT platform/CMakeFiles/platform_s.dir/home/mike/golioth-compile/circuitdojo/nrf/modules/tfm/tfm/boards/common/assert.o -MF platform/CMakeFiles/platform_s.dir/home/mike/golioth-compile/circuitdojo/nrf/modules/tfm/tfm/boards/common/assert.o.d -o platform/CMakeFiles/platform_s.dir/home/mike/golioth-compile/circuitdojo/nrf/modules/tfm/tfm/boards/common/assert.o -c /home/mike/golioth-compile/circuitdojo/nrf/modules/tfm/tfm/boards/common/assert.c
/home/mike/golioth-compile/circuitdojo/nrf/modules/tfm/tfm/boards/common/assert.c:17:2: error: #error "TF-M non-secure address start is not aligned on SPU region size"
   17 | #error "TF-M non-secure address start is not aligned on SPU region size"
      |  ^~~~~
[28/46] Building C object platform/CMakeFiles/platform_s.dir/home/mike/golioth-compile/circuitdojo/nrf/modules/tfm/tfm/boards/common/attest_hal.o
ninja: build stopped: subcommand failed.
[70/375] Generating misc/generated/syscalls.json, misc/generated/struct_tags.json
FAILED: modules/trusted-firmware-m/tfm-prefix/src/tfm-stamp/tfm-build tfm/secure_fw/s_veneers.o tfm/tf-m-tests/app/libtfm_api_ns.a tfm/generated/interface/include/psa_manifest/sid.h tfm/platform/libplatform_ns.a tfm/bin/tfm_s.elf tfm/bin/tfm_s.bin tfm/bin/tfm_s.hex tfm/bin/tfm_ns.bin tfm/bin/tfm_ns.hex tfm/bin/tfm_s_signed.bin tfm/bin/tfm_ns_signed.bin tfm/bin/tfm_s_ns_signed.bin tfm/install/interface/src/tfm_platform_ipc_api.c tfm/install/interface/src/tfm_ps_ipc_api.c tfm/install/interface/src/tfm_its_ipc_api.c tfm/install/interface/src/tfm_crypto_ipc_api.c tfm/install/interface/src/tfm_initial_attestation_ipc_api.c tfm/install/interface/src/tfm_firmware_update_ipc_api.c tfm/install/interface/src/tfm_psa_ns_api.c tfm/install/interface/src/tfm_platform_func_api.c tfm/install/interface/src/tfm_ps_func_api.c tfm/install/interface/src/tfm_its_func_api.c tfm/install/interface/src/tfm_crypto_func_api.c tfm/install/interface/src/tfm_initial_attestation_func_api.c tfm/install/interface/src/tfm_firmware_update_func_api.c tfm/install/interface/src/tfm_ioctl_core_ns_api.c /home/mike/golioth-compile/circuitdojo/nfed/samples/tracker/build/modules/trusted-firmware-m/tfm-prefix/src/tfm-stamp/tfm-build /home/mike/golioth-compile/circuitdojo/nfed/samples/tracker/build/tfm/secure_fw/s_veneers.o /home/mike/golioth-compile/circuitdojo/nfed/samples/tracker/build/tfm/tf-m-tests/app/libtfm_api_ns.a /home/mike/golioth-compile/circuitdojo/nfed/samples/tracker/build/tfm/generated/interface/include/psa_manifest/sid.h /home/mike/golioth-compile/circuitdojo/nfed/samples/tracker/build/tfm/platform/libplatform_ns.a /home/mike/golioth-compile/circuitdojo/nfed/samples/tracker/build/tfm/bin/tfm_s.elf /home/mike/golioth-compile/circuitdojo/nfed/samples/tracker/build/tfm/bin/tfm_s.bin /home/mike/golioth-compile/circuitdojo/nfed/samples/tracker/build/tfm/bin/tfm_s.hex /home/mike/golioth-compile/circuitdojo/nfed/samples/tracker/build/tfm/bin/tfm_ns.bin /home/mike/golioth-compile/circuitdojo/nfed/samples/tracker/build/tfm/bin/tfm_ns.hex /home/mike/golioth-compile/circuitdojo/nfed/samples/tracker/build/tfm/bin/tfm_s_signed.bin /home/mike/golioth-compile/circuitdojo/nfed/samples/tracker/build/tfm/bin/tfm_ns_signed.bin /home/mike/golioth-compile/circuitdojo/nfed/samples/tracker/build/tfm/bin/tfm_s_ns_signed.bin /home/mike/golioth-compile/circuitdojo/nfed/samples/tracker/build/tfm/install/interface/src/tfm_platform_ipc_api.c /home/mike/golioth-compile/circuitdojo/nfed/samples/tracker/build/tfm/install/interface/src/tfm_ps_ipc_api.c /home/mike/golioth-compile/circuitdojo/nfed/samples/tracker/build/tfm/install/interface/src/tfm_its_ipc_api.c /home/mike/golioth-compile/circuitdojo/nfed/samples/tracker/build/tfm/install/interface/src/tfm_crypto_ipc_api.c /home/mike/golioth-compile/circuitdojo/nfed/samples/tracker/build/tfm/install/interface/src/tfm_initial_attestation_ipc_api.c /home/mike/golioth-compile/circuitdojo/nfed/samples/tracker/build/tfm/install/interface/src/tfm_firmware_update_ipc_api.c /home/mike/golioth-compile/circuitdojo/nfed/samples/tracker/build/tfm/install/interface/src/tfm_psa_ns_api.c /home/mike/golioth-compile/circuitdojo/nfed/samples/tracker/build/tfm/install/interface/src/tfm_platform_func_api.c /home/mike/golioth-compile/circuitdojo/nfed/samples/tracker/build/tfm/install/interface/src/tfm_ps_func_api.c /home/mike/golioth-compile/circuitdojo/nfed/samples/tracker/build/tfm/install/interface/src/tfm_its_func_api.c /home/mike/golioth-compile/circuitdojo/nfed/samples/tracker/build/tfm/install/interface/src/tfm_crypto_func_api.c /home/mike/golioth-compile/circuitdojo/nfed/samples/tracker/build/tfm/install/interface/src/tfm_initial_attestation_func_api.c /home/mike/golioth-compile/circuitdojo/nfed/samples/tracker/build/tfm/install/interface/src/tfm_firmware_update_func_api.c /home/mike/golioth-compile/circuitdojo/nfed/samples/tracker/build/tfm/install/interface/src/tfm_ioctl_core_ns_api.c 
cd /home/mike/golioth-compile/circuitdojo/nfed/samples/tracker/build/tfm && /home/mike/.zephyrtools/cmake/cmake-3.22.0-linux-x86_64/bin/cmake --build .
ninja: build stopped: subcommand failed.
FATAL ERROR: command exited with status 1: /home/mike/.zephyrtools/cmake/cmake-3.22.0-linux-x86_64/bin/cmake --build /home/mike/golioth-compile/circuitdojo/nfed/samples/tracker/build
```

This has already been reported to Nordic, including by others building for the circuitdojo feather:
https://devzone.nordicsemi.com/f/nordic-q-a/97720/tf-m-partition-alignment-assert-within-spu-might-fail-for-some-partition-manager-computed-configs

I'm reporting it here for visibility.

## Attempted Manual workaround:

**EDIT:** this will build but the app doesn't run once programmed so the partition table is likely incorrect with the workaround as I have it.

I tried to workaround this issue following the advice from the thread linked above:

1. Build the project (build will fail with this error)
2. copy `build/partitions.yml` to `pm_static.yml` in the `tracker` folder
3. Edit `pm_static.yml` to remove the 0x200 address offset in `app:` and `tfm_nonsecure: `secitons`
   * the address entry for both of those section should now be: `address: 0x20000`
4. Rerun the build command and it will succeed.

My corrected partitions file is as folows:

```yaml
EMPTY_0:
  address: 0xc000
  end_address: 0x10000
  placement:
    before:
    - mcuboot_pad
  region: flash_primary
  size: 0x4000
EMPTY_1:
  address: 0xfe000
  end_address: 0x100000
  placement:
    after:
    - littlefs_storage
  region: flash_primary
  size: 0x2000
app:
  address: 0x20000
  end_address: 0xf8000
  region: flash_primary
  size: 0xd7e00
external_flash:
  address: 0xe8000
  end_address: 0x400000
  region: external_flash
  size: 0x318000
littlefs_storage:
  address: 0xf8000
  end_address: 0xfe000
  inside:
  - nonsecure_storage
  placement:
    align:
      start: 0x8000
    before:
    - end
  region: flash_primary
  size: 0x6000
mcuboot:
  address: 0x0
  end_address: 0xc000
  placement:
    before:
    - mcuboot_primary
  region: flash_primary
  size: 0xc000
mcuboot_pad:
  address: 0x10000
  end_address: 0x10200
  placement:
    align:
      start: 0x8000
    before:
    - mcuboot_primary_app
  region: flash_primary
  size: 0x200
mcuboot_primary:
  address: 0x10000
  end_address: 0xf8000
  orig_span: &id001
  - app
  - mcuboot_pad
  - tfm
  region: flash_primary
  size: 0xe8000
  span: *id001
mcuboot_primary_app:
  address: 0x10200
  end_address: 0xf8000
  orig_span: &id002
  - app
  - tfm
  region: flash_primary
  size: 0xe7e00
  span: *id002
mcuboot_secondary:
  address: 0x0
  device: DT_CHOSEN(nordic_pm_ext_flash)
  end_address: 0xe8000
  placement:
    align:
      start: 0x4
  region: external_flash
  share_size:
  - mcuboot_primary
  size: 0xe8000
mcuboot_sram:
  address: 0x20000000
  end_address: 0x20008000
  orig_span: &id003
  - tfm_sram
  region: sram_primary
  size: 0x8000
  span: *id003
nonsecure_storage:
  address: 0xf8000
  end_address: 0xfe000
  orig_span: &id004
  - littlefs_storage
  region: flash_primary
  size: 0x6000
  span: *id004
nrf_modem_lib_ctrl:
  address: 0x20008000
  end_address: 0x200084e8
  inside:
  - sram_nonsecure
  placement:
    after:
    - tfm_sram
    - start
  region: sram_primary
  size: 0x4e8
nrf_modem_lib_rx:
  address: 0x2000a568
  end_address: 0x2000c568
  inside:
  - sram_nonsecure
  placement:
    after:
    - nrf_modem_lib_tx
  region: sram_primary
  size: 0x2000
nrf_modem_lib_sram:
  address: 0x20008000
  end_address: 0x2000c568
  orig_span: &id005
  - nrf_modem_lib_ctrl
  - nrf_modem_lib_tx
  - nrf_modem_lib_rx
  region: sram_primary
  size: 0x4568
  span: *id005
nrf_modem_lib_tx:
  address: 0x200084e8
  end_address: 0x2000a568
  inside:
  - sram_nonsecure
  placement:
    after:
    - nrf_modem_lib_ctrl
  region: sram_primary
  size: 0x2080
otp:
  address: 0xff8108
  end_address: 0xff83fc
  region: otp
  size: 0x2f4
sram_nonsecure:
  address: 0x20008000
  end_address: 0x20040000
  orig_span: &id006
  - sram_primary
  - nrf_modem_lib_ctrl
  - nrf_modem_lib_tx
  - nrf_modem_lib_rx
  region: sram_primary
  size: 0x38000
  span: *id006
sram_primary:
  address: 0x2000c568
  end_address: 0x20040000
  region: sram_primary
  size: 0x33a98
sram_secure:
  address: 0x20000000
  end_address: 0x20008000
  orig_span: &id007
  - tfm_sram
  region: sram_primary
  size: 0x8000
  span: *id007
tfm:
  address: 0x10200
  end_address: 0x20200
  inside:
  - mcuboot_primary_app
  placement:
    before:
    - app
  region: flash_primary
  size: 0x10000
tfm_nonsecure:
  address: 0x20000
  end_address: 0xf8000
  orig_span: &id008
  - app
  region: flash_primary
  size: 0xd7e00
  span: *id008
tfm_secure:
  address: 0x10000
  end_address: 0x20200
  orig_span: &id009
  - mcuboot_pad
  - tfm
  region: flash_primary
  size: 0x10200
  span: *id009
tfm_sram:
  address: 0x20000000
  end_address: 0x20008000
  inside:
  - sram_secure
  placement:
    after:
    - start
  region: sram_primary
  size: 0x8000
```
